<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statememory"
    nsURI="http://www.cwi.nl/ea/stateMemory" nsPrefix="statememory">
  <eClassifiers xsi:type="ecore:EClass" name="StateMemory" eSuperTypes="platform:/plugin/org.ect.ea/model/ea.ecore#//extensions/StringListExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializations" upperBound="-1"
        eType="#//StringMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
