<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mcrl2"
    nsURI="http://www.cwi.nl/mcrl2" nsPrefix="mcrl2">
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atoms" upperBound="-1"
        eType="#//Atom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//Process" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sorts" upperBound="-1"
        eType="#//Sort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sort" abstract="true" interface="true">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveSort" eSuperTypes="#//Nameable #//Sort"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserSort" eSuperTypes="#//Nameable #//Sort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="#//Nameable #//Sort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Atom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Atom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomProcess" eSuperTypes="#//Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Sort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atom" eType="#//Atom"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeAction" abstract="true" eSuperTypes="#//Action">
    <eOperations name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchronization" eSuperTypes="#//CompositeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parallelism" eSuperTypes="#//CompositeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//CompositeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//CompositeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//Process"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implication" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseAction" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implications" upperBound="-1"
        eType="#//Implication" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parallelism" eType="#//Parallelism"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allow" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atoms" upperBound="-1"
        eType="#//Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atoms" upperBound="-1"
        eType="#//Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hide" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atoms" upperBound="-1"
        eType="#//Atom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Summation" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Atom" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
