/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.ect.ea.costs.types.validation;


/**
 * A sample validator interface for {@link org.ect.ea.costs.types.StringCosts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StringCostsValidator {
	boolean validate();

	boolean validateStringValue(String value);
}
